#!/bin/bash

cd /tmp/rom # Depends on where source got synced
find .repo/ -delete


curl https://nekobin.com/siwarifiwi >> gms_full.mk
mv gms_full.mk vendor/gms/*
rm -rf device/generic/opengl-transport

# Normal build steps
. build/envsetup.sh
lunch derp_daisy-userdebug
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
export SKIP_BOOT_JARS_CHECK=true && export WITHOUT_CHECK_API=true
ccache -M 60G # It took only 6.4GB for mido
ccache -o compression=true # Will save times and data to download and upload ccache, also negligible performance issue
ccache -z # Clear old stats, so monitor script will provide real ccache statistics

# upload function for uploading rom zip file! I don't want unwanted builds in my google drive haha!
up(){
	curl --upload-file $1 https://transfer.sh/
}

# Build command! j10 for 10 cpu, j8 for 8 cpu, otherwise memeroy will end up even its 24G
# Upload rom zip file if succeed to build! Send notification to tg! And send shell to tg if build fails!

# Let's compile by parts! Coz of ram issue!
# make api-stubs-docs || echo no problem
make hiddenapi-lists-docs || echo no problem
make system-api-stubs-docs || echo no problem
make test-api-stubs-docs || echo no problem

mka derp -j8 &
sleep 70m
kill %1
ccache -s
